sources:
  farming:
    wheat: 5.0
    potato: 5.5
    carrot: 5.7
    beetroot: 10.0
    nether_wart: 10.0
    pumpkin: 15.4
    melon: 13.4
    sugar_cane: 11.7
    bamboo: 10.25
    cocoa: 14.0
    cactus: 16.0
    brown_mushroom: 17.0
    red_mushroom: 17.0
    kelp: 10.3
    sea_pickle: 14.0
    sweet_berry_bush: 12.5
    glow_berries: 14.5
  foraging:
    oak_log: 14.0
    spruce_log: 14.0
    birch_log: 14.0
    jungle_log: 14.0
    acacia_log: 14.0
    dark_oak_log: 14.0
    mangrove_log: 14.0
    oak_leaves: 10.4
    spruce_leaves: 10.4
    birch_leaves: 10.4
    jungle_leaves: 10.4
    acacia_leaves: 10.4
    dark_oak_leaves: 10.4
    mangrove_leaves: 10.4
    crimson_stem: 15.0
    warped_stem: 15.0
    nether_wart_block: 10.5
    warped_wart_block: 10.5
    moss_block: 13.2
    moss_carpet: 10.2
    azalea: 17.0
    flowering_azalea: 19.1
    azalea_leaves: 11.5
    flowering_azalea_leaves: 12.0
    mangrove_roots: 12.0
  mining:
    stone: 5.2
    cobblestone: 10.2
    andesite: 15.2
    diorite: 15.2
    granite: 15.2
    coal_ore: 15.0
    nether_quartz_ore: 5.8
    iron_ore: 20.8
    lapis_ore: 150.6
    redstone_ore: 15.9
    gold_ore: 30.8
    diamond_ore: 500.3
    emerald_ore: 1000.0
    terracotta: 10.5
    white_terracotta: 10.5
    orange_terracotta: 10.5
    yellow_terracotta: 10.5
    light_gray_terracotta: 10.5
    brown_terracotta: 10.5
    red_terracotta: 10.5
    netherrack: 10.1
    blackstone: 10.3
    basalt: 10.4
    magma_block: 10.7
    nether_gold_ore: 110.0
    ancient_debris: 1500.0
    end_stone: 10.5
    obsidian: 110.0
    deepslate: 10.4
    copper_ore: 13.5
    tuff: 10.5
    calcite: 10.8
    smooth_basalt: 10.8
    amethyst_block: 14.0
    amethyst_cluster: 16.0
    deepslate_coal_ore: 11.2
    deepslate_iron_ore: 12.2
    deepslate_copper_ore: 14.2
    deepslate_gold_ore: 121.4
    deepslate_redstone_ore: 17.1
    deepslate_lapis_ore: 136.7
    deepslate_emerald_ore: 1120.0
    deepslate_diamond_ore: 156.8
    dripstone_block: 13.2
    ice: 10.3
    packed_ice: 10.8
    blue_ice: 11.3
    reinforced_deepslate: 1125.0
  fishing:
    cod: 25.0
    salmon: 60.0
    tropical_fish: 750.0
    pufferfish: 115.0
    treasure: 1000.0
    junk: 30.0
    rare: 2000.0
    epic: 5000.0
  excavation:
    dirt: 10.3
    grass_block: 10.7
    sand: 10.4
    gravel: 11.5
    mycelium: 13.7
    clay: 12.4
    soul_sand: 12.7
    coarse_dirt: 12.3
    podzol: 12.5
    soul_soil: 13.0
    red_sand: 10.7
    rooted_dirt: 15.6
    mud: 10.5
    muddy_mangrove_roots: 12.5
  archery:
    player: 50.0
    bat: 1.0
    cat: 1.0
    chicken: 1.0
    cod: 1.0
    cow: 2.0
    donkey: 2.0
    fox: 3.0
    giant: 10.0
    horse: 2.0
    mooshroom: 2.0
    mule: 2.0
    ocelot: 1.0
    parrot: 1.0
    pig: 2.0
    rabbit: 1.0
    salmon: 1.0
    sheep: 2.0
    skeleton_horse: 3.0
    snow_golem: 3.0
    squid: 2.0
    strider: 3.0
    tropical_fish: 1.0
    turtle: 2.0
    villager: 2.0
    wandering_trader: 2.0
    bee: 3.0
    cave_spider: 5.0
    dolphin: 3.0
    enderman: 7.0
    iron_golem: 17.0
    llama: 4.0
    piglin: 5.0
    panda: 5.0
    polar_bear: 7.0
    pufferfish: 1.0
    spider: 5.0
    wolf: 4.0
    zombified_piglin: 4.0
    blaze: 10.0
    creeper: 10.0
    drowned: 7.0
    elder_guardian: 100.0
    endermite: 5.0
    evoker: 35.0
    ghast: 17.0
    guardian: 15.0
    hoglin: 12.0
    husk: 7.0
    illusioner: 17.0
    magma_cube: 12.0
    phantom: 10.0
    piglin_brute: 35.0
    pillager: 12.0
    ravager: 100.0
    shulker: 15.0
    silverfish: 5.0
    skeleton: 7.0
    slime: 5.0
    stray: 8.0
    vex: 10.0
    vindicator: 12.0
    witch: 9.0
    wither_skeleton: 17.0
    zoglin: 12.0
    zombie: 7.0
    zombie_villager: 7.0
    ender_dragon: 7000.0
    wither: 7000.0
    axolotl: 3.5
    glow_squid: 2.5
    goat: 3.0
    allay: 0.2
    frog: 2.0
    tadpole: 0.7
    warden: 10000.0
  defense:
    mob_damage: 1
    player_damage: 2
  fighting:
    player: 1000.0
    bat: 11.0
    cat: 11.0
    chicken: 11.0
    cod: 11.0
    cow: 12.0
    donkey: 12.0
    fox: 13.0
    giant: 110.0
    horse: 12.0
    mooshroom: 12.0
    mule: 12.0
    ocelot: 11.0
    parrot: 11.0
    pig: 12.0
    rabbit: 11.0
    salmon: 11.0
    sheep: 12.0
    skeleton_horse: 13.0
    snow_golem: 13.0
    squid: 12.0
    strider: 13.0
    tropical_fish: 11.0
    turtle: 21.0
    villager: 21.0
    wandering_trader: 21.0
    bee: 30.0
    cave_spider: 50.0
    dolphin: 30.0
    enderman: 70.0
    iron_golem: 107.0
    llama: 40.0
    piglin: 50.0
    panda: 50.0
    polar_bear: 70.0
    pufferfish: 10.0
    spider: 50.0
    wolf: 40.0
    zombified_piglin: 40.0
    blaze: 100.0
    creeper: 100.0
    drowned: 70.0
    elder_guardian: 1000.0
    endermite: 50.0
    evoker: 350.0
    ghast: 170.0
    guardian: 150.0
    hoglin: 120.0
    husk: 70.0
    illusioner: 170.0
    magma_cube: 120.0
    phantom: 100.0
    piglin_brute: 35.0
    pillager: 12.0
    ravager: 100.0
    shulker: 150.0
    silverfish: 50.0
    skeleton: 70.0
    slime: 5.0
    stray: 8.0
    vex: 10.0
    vindicator: 12.0
    witch: 9.0
    wither_skeleton: 17.0
    zoglin: 12.0
    zombie: 7.0
    zombie_villager: 7.0
    ender_dragon: 70000.0
    wither: 70000.0
    axolotl: 3.5
    glow_squid: 2.5
    goat: 3.0
    allay: 0.2
    frog: 2.0
    tadpole: 1.2
    warden: 150000.0
  endurance:
    walk_per_meter: 0.333
    sprint_per_meter: 0.1
    swim_per_meter: 1
  agility:
    jump_per_100: 10
    fall_damage: 2
  alchemy:
    awkward: 50
    regular: 100
    extended: 500
    upgraded: 1000
    splash: 1500
    lingering: 3000
  enchanting:
    weapon_per_level: 20
    armor_per_level: 20
    tool_per_level: 20
    book_per_level: 20
  sorcery:
    mana_ability_use: 0.5
    sculk: 1.0
    sculk_catalyst: 12.0
    sculk_shrieker: 27.0
    sculk_vein: 0.5
    sculk_sensor: 8.0
  healing:
    drink_regular: 10
    drink_extended: 15
    drink_upgraded: 15
    splash_regular: 20
    splash_extended: 25
    splash_upgraded: 25
    lingering_regular: 30
    lingering_extended: 35
    lingering_upgraded: 35
    golden_apple: 5
    enchanted_golden_apple: 50
  forging:
    combine_books_per_level: 10
    combine_weapon_per_level: 15
    combine_armor_per_level: 20
    combine_tool_per_level: 25
    grindstone_per_level: 30
tags:
  farming:
    bountiful_harvest_applicable:
      - '*'
    triple_harvest_applicable:
      - '*'
  foraging:
    lumberjack_applicable:
      - '*'
  mining:
    lucky_miner_applicable:
      - coal_ore
      - nether_quartz_ore
      - iron_ore
      - redstone_ore
      - lapis_ore
      - gold_ore
      - diamond_ore
      - emerald_ore
      - nether_gold_ore
      - ancient_debris
      - copper_ore
      - deepslate_coal_ore
      - deepslate_iron_ore
      - deepslate_copper_ore
      - deepslate_gold_ore
      - deepslate_redstone_ore
      - deepslate_lapis_ore
      - deepslate_emerald_ore
      - deepslate_diamond_ore
    speed_mine_applicable:
      - '*'
  excavation:
    dirts:
      - dirt
      - podzol
      - coarse_dirt
      - rooted_dirt
      - mycelium
      - grass_block
    bigger_scoop_applicable:
      - '*'
    metal_detector_applicable:
      - '*'
    lucky_spades_applicable:
      - '*'
    terraform_applicable:
      - '*'
file_version: 8