sources:
  farming:
    wheat: 50.0
    potato: 50.5
    carrot: 50.7
    beetroot: 100.0
    nether_wart: 100.0
    pumpkin: 500.4
    melon: 500.4
    sugar_cane: 50.7
    bamboo: 300.25
    cocoa: 500.0
    cactus: 1000.0
    brown_mushroom: 170.0
    red_mushroom: 170.0
    kelp: 100.3
    sea_pickle: 140.0
    sweet_berry_bush: 120.5
    glow_berries: 140.5
  foraging:
    oak_log: 140.0
    spruce_log: 140.0
    birch_log: 140.0
    jungle_log: 140.0
    acacia_log: 140.0
    dark_oak_log: 140.0
    mangrove_log: 140.0
    oak_leaves: 100.4
    spruce_leaves: 100.4
    birch_leaves: 100.4
    jungle_leaves: 100.4
    acacia_leaves: 100.4
    dark_oak_leaves: 100.4
    mangrove_leaves: 100.4
    crimson_stem: 150.0
    warped_stem: 150.0
    nether_wart_block: 100.5
    warped_wart_block: 100.5
    moss_block: 130.2
    moss_carpet: 100.2
    azalea: 170.0
    flowering_azalea: 190.1
    azalea_leaves: 110.5
    flowering_azalea_leaves: 120.0
    mangrove_roots: 120.0
  mining:
    stone: 100.2
    cobblestone: 100.2
    andesite: 150.2
    diorite: 150.2
    granite: 150.2
    coal_ore: 150.0
    nether_quartz_ore: 50.8
    iron_ore: 200.8
    lapis_ore: 1500.6
    redstone_ore: 1500.9
    gold_ore: 300.8
    diamond_ore: 5000.3
    emerald_ore: 10000.0
    terracotta: 100.5
    white_terracotta: 100.5
    orange_terracotta: 100.5
    yellow_terracotta: 100.5
    light_gray_terracotta: 100.5
    brown_terracotta: 100.5
    red_terracotta: 100.5
    netherrack: 100.1
    blackstone: 100.3
    basalt: 100.4
    magma_block: 100.7
    nether_gold_ore: 1100.0
    ancient_debris: 15000.0
    end_stone: 100.5
    obsidian: 1100.0
    deepslate: 100.4
    copper_ore: 130.5
    tuff: 100.5
    calcite: 100.8
    smooth_basalt: 100.8
    amethyst_block: 140.0
    amethyst_cluster: 106.0
    deepslate_coal_ore: 110.2
    deepslate_iron_ore: 120.2
    deepslate_copper_ore: 140.2
    deepslate_gold_ore: 121.4
    deepslate_redstone_ore: 17.1
    deepslate_lapis_ore: 136.7
    deepslate_emerald_ore: 1120.0
    deepslate_diamond_ore: 156.8
    dripstone_block: 13.2
    ice: 10.3
    packed_ice: 10.8
    blue_ice: 11.3
    reinforced_deepslate: 1125.0
  fishing:
    cod: 250.0
    salmon: 600.0
    tropical_fish: 7500.0
    pufferfish: 1150.0
    treasure: 10000.0
    junk: 300.0
    rare: 2000.0
    epic: 5000.0
  excavation:
    dirt: 150.3
    grass_block: 150.7
    sand: 200.4
    gravel: 200.5
    mycelium: 200.7
    clay: 300.4
    soul_sand: 300.7
    coarse_dirt: 300.3
    podzol: 300.5
    soul_soil: 300.0
    red_sand: 300.7
    rooted_dirt: 300.6
    mud: 300.5
    muddy_mangrove_roots: 300.5
  archery:
    player: 10000.0
    bat: 10.0
    cat: 10.0
    chicken: 50.0
    cod: 40.0
    cow: 60.0
    donkey: 50.0
    fox: 100.0
    giant: 100.0
    horse: 100.0
    mooshroom: 100.0
    mule: 100.0
    ocelot: 100.0
    parrot: 100.0
    pig: 120.0
    rabbit: 110.0
    salmon: 110.0
    sheep: 120.0
    skeleton_horse: 5300.0
    snow_golem: 130.0
    squid: 120.0
    strider: 130.0
    tropical_fish: 110.0
    turtle: 210.0
    villager: 50.0
    wandering_trader: 51.0
    bee: 50.0
    cave_spider: 50.0
    dolphin: 30.0
    enderman: 70.0
    iron_golem: 107.0
    llama: 40.0
    piglin: 50.0
    panda: 50.0
    polar_bear: 70.0
    pufferfish: 10.0
    spider: 50.0
    wolf: 40.0
    zombified_piglin: 40.0
    blaze: 100.0
    creeper: 100.0
    drowned: 70.0
    elder_guardian: 1000.0
    endermite: 50.0
    evoker: 350.0
    ghast: 170.0
    guardian: 150.0
    hoglin: 120.0
    husk: 70.0
    illusioner: 170.0
    magma_cube: 120.0
    phantom: 100.0
    piglin_brute: 350.0
    pillager: 120.0
    ravager: 100.0
    shulker: 150.0
    silverfish: 50.0
    skeleton: 70.0
    slime: 500.0
    stray: 80.0
    vex: 100.0
    vindicator: 120.0
    witch: 90.0
    wither_skeleton: 170.0
    zoglin: 120.0
    zombie: 150.0
    zombie_villager: 700.0
    ender_dragon: 570000.0
    wither: 570000.0
    axolotl: 30.5
    glow_squid: 20.5
    goat: 30.0
    allay: 30.2
    frog: 20.0
    tadpole: 100.2
    warden: 9150000.0
  defense:
    mob_damage: 30000
    player_damage: 50000
  fighting:
    player: 10000.0
    bat: 10.0
    cat: 10.0
    chicken: 50.0
    cod: 40.0
    cow: 60.0
    donkey: 50.0
    fox: 100.0
    giant: 100.0
    horse: 100.0
    mooshroom: 100.0
    mule: 100.0
    ocelot: 100.0
    parrot: 100.0
    pig: 120.0
    rabbit: 110.0
    salmon: 110.0
    sheep: 120.0
    skeleton_horse: 5300.0
    snow_golem: 130.0
    squid: 120.0
    strider: 130.0
    tropical_fish: 110.0
    turtle: 210.0
    villager: 50.0
    wandering_trader: 51.0
    bee: 50.0
    cave_spider: 50.0
    dolphin: 30.0
    enderman: 70.0
    iron_golem: 107.0
    llama: 40.0
    piglin: 50.0
    panda: 50.0
    polar_bear: 70.0
    pufferfish: 10.0
    spider: 50.0
    wolf: 40.0
    zombified_piglin: 40.0
    blaze: 100.0
    creeper: 100.0
    drowned: 70.0
    elder_guardian: 1000.0
    endermite: 50.0
    evoker: 350.0
    ghast: 170.0
    guardian: 150.0
    hoglin: 120.0
    husk: 70.0
    illusioner: 170.0
    magma_cube: 120.0
    phantom: 100.0
    piglin_brute: 350.0
    pillager: 120.0
    ravager: 100.0
    shulker: 150.0
    silverfish: 50.0
    skeleton: 70.0
    slime: 500.0
    stray: 80.0
    vex: 100.0
    vindicator: 120.0
    witch: 90.0
    wither_skeleton: 170.0
    zoglin: 120.0
    zombie: 150.0
    zombie_villager: 700.0
    ender_dragon: 570000.0
    wither: 570000.0
    axolotl: 30.5
    glow_squid: 20.5
    goat: 30.0
    allay: 30.2
    frog: 20.0
    tadpole: 100.2
    warden: 3150000.0
  endurance:
    walk_per_meter: 100.333
    sprint_per_meter: 200.1
    swim_per_meter: 100
  agility:
    jump_per_100: 100
    fall_damage: 200
  alchemy:
    awkward: 5000
    regular: 10000
    extended: 30000
    upgraded: 50000
    splash: 30000
    lingering: 50000
  enchanting:
    weapon_per_level: 8000
    armor_per_level: 8000
    tool_per_level: 8000
    book_per_level: 8000
  sorcery:
    mana_ability_use: 1000.5
    sculk: 1000.0
    sculk_catalyst: 1200.0
    sculk_shrieker: 2700.0
    sculk_vein: 1000.5
    sculk_sensor: 800.0
  healing:
    drink_regular: 5000
    drink_extended: 10000
    drink_upgraded: 20000
    splash_regular: 30000
    splash_extended: 40000
    splash_upgraded: 40000
    lingering_regular: 30000
    lingering_extended: 30000
    lingering_upgraded: 30000
    golden_apple: 1000
    enchanted_golden_apple: 5000
  forging:
    combine_books_per_level: 5000
    combine_weapon_per_level: 6500
    combine_armor_per_level: 10000
    combine_tool_per_level: 6500
    grindstone_per_level: 10000
tags:
  farming:
    bountiful_harvest_applicable:
      - '*'
    triple_harvest_applicable:
      - '*'
  foraging:
    lumberjack_applicable:
      - '*'
  mining:
    lucky_miner_applicable:
      - coal_ore
      - nether_quartz_ore
      - iron_ore
      - redstone_ore
      - lapis_ore
      - gold_ore
      - diamond_ore
      - emerald_ore
      - nether_gold_ore
      - ancient_debris
      - copper_ore
      - deepslate_coal_ore
      - deepslate_iron_ore
      - deepslate_copper_ore
      - deepslate_gold_ore
      - deepslate_redstone_ore
      - deepslate_lapis_ore
      - deepslate_emerald_ore
      - deepslate_diamond_ore
    speed_mine_applicable:
      - '*'
  excavation:
    dirts:
      - dirt
      - podzol
      - coarse_dirt
      - rooted_dirt
      - mycelium
      - grass_block
    bigger_scoop_applicable:
      - '*'
    metal_detector_applicable:
      - '*'
    lucky_spades_applicable:
      - '*'
    terraform_applicable:
      - '*'
file_version: 8