# Плейсхолдер титлменеджера https://tmdocs.tarkan.dev/admins/config
# Плейсхолдер лист https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#advancements
# Версия плагина 2.3.6


############################################################
# +------------------------------------------------------+ #
# |                       Основное                       | #
# +------------------------------------------------------+ #
############################################################

# Не трогать!
config-version: 7

# Включает режим отладки, в котором печатается дополнительная информация, когда плагин что-то делает.
debug: false

# Переключает, будут ли переключены все функции TitleManager.
using-config: true

# Переключает, будет ли переключена вся функциональность BungeeCord.
using-bungeecord: false

# (Функция работает только на 1.7-1.8 Protocol Hack)
# Переключает, будут ли игроки 1.7 видеть сообщения на панели действий, когда они держат предмет.
legacy-client-support: false

# Переключает, должен ли плагин предупреждать администраторов о выходе новой версии.
check-for-updates: false

# Локально, используемая для некоторых плейсхолдеров.
locale: 'en-US'

############################################################
# +------------------------------------------------------+ #
# |                     Список игроков                   | #
# +------------------------------------------------------+ #
############################################################

# Устанавливает верхний и нижний колонтитулы списка плееров. (Отображается при нажатой клавише TAB).
player-list:

# Включает эту функцию.
  enabled: true

  # Устанавливает заголовок списка игроков.
  #
  # Однострочный формат.
  # header: 'My header text'
  #
  # Многострочный формат.
  # header:
  # - 'Моя первая строка'
  # - 'Моя вторая строка'
  # - 'Моя третья строка'
  header:
  - ''
  - '${shine:[0;2;0][0;25;0][0;25;0][&3;&b]Tryp Team}'
  - ''

 # Устанавливает нижний колонтитул списка игроков.
  #
  # Однострочный формат.
  # footer: 'My footer text'
  #
  # Формат нескольких строк.
  # footer:
  # - 'Моя первая строка'
  # - 'Моя вторая строка'
  # - 'Моя третья строка'
  footer:
  - ''
  - '&7Час: &b%{12h-world-time}'
  - '&7Ігровий час: &b%{server-time}'
  - ''
  - '${right-to-left} &b%{online}&7/&b%{max} &7Гравців онлайн ${left-to-right}'

############################################################
# +------------------------------------------------------+ #
# |                    Приветственное название           | #
# +------------------------------------------------------+ #
############################################################

# Устанавливает заголовок, который отправляется игроку, когда он присоединяется к серверу.

welcome-title:

# Включает эту функцию.
  enabled: true

# Отображаемый заголовок.
  title: 'Вітаю'

# Отображаемый субтитр.
  subtitle: 'Сподіваємось, вам сподобається'

# Время затухания заголовка на экране. (В тиках)
  fade-in: 20

  # Время, в течение которого заголовок остается на экране. (В тиках)
  stay: 40

  # Время, за которое заголовок исчезает с экрана. (В тиках)
  fade-out: 20

  # Время появления заголовков на экране. (В тиках)
  delay: 20

  # Заголовок, показываемый, когда игрок впервые присоединяется к серверу.
  first-join:

  # Отображаемый заголовок.
    title: 'Вітаю'

    # Отображаемый подзаголовок.
    subtitle: 'Вітаю!'

############################################################
# +------------------------------------------------------+ #
# |                  Панель приветствия                  | #
# +------------------------------------------------------+ #
############################################################

# Устанавливает панель действий, которая отправляется игроку, когда он присоединяется к серверу.

welcome-actionbar:

# Включает эту функцию.
  enabled: true

# Выводимое сообщение.
  title: 'Вітаю'

# Время, необходимое для появления сообщения. (В тиках)
  delay: 20

# Сообщение, показываемое при первом присоединении игрока к серверу.
  first-join: 'Вітаю!'

############################################################
# +------------------------------------------------------+ #
# |                     Плейсхолдер                      | #
# +------------------------------------------------------+ #
############################################################

# Настраивает все, что связано с placeholder.

placeholders:

# Формат, используемый заполнителем баланса.
  number-format:

    # Включает эту функцию.
    enabled: true

    # Используемый формат.
    format: '#,###.##'

  # Формат, используемый для размещения серверного времени.
  # Используемый формат можно найти здесь: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
  date-format: 'EEE, dd MMM yyyy HH:mm:ss z'

############################################################
# +------------------------------------------------------+ #
# |                      Скорбоард                       | #
# +------------------------------------------------------+ #
############################################################

# Устанавливает табло (боковую панель), которое передается игроку

scoreboard:

# Включает эту функцию
  enabled: true

# Заголовок, отображаемый в самом верху табло
  # ВНИМАНИЕ! (ТОЛЬКО для версии 1.12 и ниже) Заголовок должен состоять из 32 или менее символов (включая коды цветов)
  title: '${shine:[0;2;0][0;25;0][0;25;0][&3&l;&b&l]Tryp Team}'

  # Строки табло (допускается не более 15 строк)
  lines:
  - '&b&m----------------------------------'
  - '&b> &3&lPlayer Name:'
  - '&b%{name}'
  - '&r'
  - '&b> &3&lPing:'
  - '&b%{ping} MS'
  - '&r&r'
  - '&b> &3&lServer Time:'
  - '&b%{server-time}'
  - '&b&m----------------------------------&r'

# Список миров, в которых табло не должно отображаться.
  disabled-worlds:
  - 'my-disabled-world'
  - 'my-disabled-world-nether'

############################################################
# +------------------------------------------------------+ #
# |                      Анонс                           | #
# +------------------------------------------------------+ #
############################################################

# Автоматическая отправка титров и/или сообщений actionbar игрокам на сервере.

announcer:

  # Включает эту функцию.
  enabled: false

  # Анонсы.
  #
  # Формат:
  #
  # announcement-name:
  # interval: 60 (Seconds, Default: 60)
  # timings:
  # fade-in: 20 (Тиков, По умолчанию: 20)
  # stay: 40 (Ticks, Default: 40)
  # fade-out: 20 (Ticks, Default: 20)
  # titles:
  # - 'First title' (Отправляемый заголовок)
  # - 'Second title\nSecond subtitle' (Отправляется следующий заголовок, на этот раз с использованием \n для разделения заголовка и подзаголовка друг от друга)
  # actionbar:
  # - 'First actionbar' (Отправлено сообщение actionbar)
  # - 'The next actionbar sent' (Отправлено следующее сообщение actionbar)
  announcements:
    my-announcement:
      interval: 60
      timings:
        fade-in: 20
        stay: 40
        fade-out: 20
      titles:
      - '&aThis is the 1st title announcement\n&aThis is the subtitle'
      - '&bThis is the 2nd title announcement\n&bThis is the subtitle'
      actionbar:
      - '&aThis is the 1st actionbar announcement'
      - '&bThis is the 2nd actionbar announcement'

############################################################
# +------------------------------------------------------+ #
# |                       Пропускной канал               | #
# +------------------------------------------------------+ #
############################################################

# Конфигурирует все параметры экономии пропускной способности.

bandwidth:
  # Предотвращает отправку одинаковых пакетов, снижая пропускную способность (но может быть более требовательным к процессору).
  prevent-duplicate-packets: true

  # Скорость тикания списка игроков в миллисекундах. (Меньше = больше пропускная способность и использование процессора, больше = меньше пропускная способность и использование процессора)
  player-list-ms-per-tick: 50

  # Частота тиков табло в миллисекундах. (Меньше = больше пропускная способность и использование процессора, больше = меньше пропускная способность и использование процессора)
  scoreboard-ms-per-tick: 50

############################################################
# +------------------------------------------------------+ #
# | Plugin Hooks | #
# +------------------------------------------------------+ #
############################################################

# Позволяет включать и отключать определенные хуки.
hooks:
  combatlogx: true

############################################################
# +------------------------------------------------------+ #
# |                       Сообщение                      | #
# +------------------------------------------------------+ #
############################################################

# Настраивает все сообщения, отправляемые пользователям.

messages:
# Сообщение, показываемое, когда у игрока нет разрешения на выполнение команды.
  no-permission: '&Ви не маєте дозволу на запуск цієї команди!'

# Сообщения от команды /tm version
  command-version:
    description: 'Показує поточну версію TitleManager'
    version: '&Сервер запущено %version'

  # Сообщения от команды /tm reload
  command-reload:
    description: 'Перезавантажує TitleManager'
    reloaded: '&aTitleManager перезавантажено'

  # Сообщения от команды /tm animations
  command-animations:
    description: 'Відображає всі завантажені анімації'
    format: '&aЗавантажені анімації (&f%count&a): %animations'
    separator: '&f, &a'

  # Сообщения от команды /tm scripts
  command-scripts:
    description: 'Відображає всі завантажені скрипти'
    format: '&aЗавантажені скрипти (&f%count&a): %scripts'
    separator: '&f, &a'

  # Сообщения от команды /tm broadcast
  command-broadcast:
    description: 'Трансляція заголовка на сервер'
    usage: '<title>|<title\nsubtitle>'
    title-sent: '&aВи транслювали назву "&r%title&a".'
    subtitle-sent: '&aВи транслювали субтитри "&r%subtitle&a".'
    both-sent: '&aВи транслювали заголовки "&r%title&a" "&r%subtitle&a".'

  # Сообщения от команды /tm abroadcast
  command-abroadcast:
    description: 'Трансляція заголовка панелі дій на сервер'
    usage: '<title>'
    sent: '&aВи транслювали заголовок панелі дій "&r%title&a".'

  # Сообщения от команды /tm message
  command-message:
    description: 'Надсилає заголовок вказаному гравцеві'
    usage: '<player> <title>|<title\nsubtitle>'
    title-sent: '&aВи надіслали %player назва "&r%title&a".'
    subtitle-sent: '&aВи надіслали %player підзаголовок "&r%subtitle&a".'
    both-sent: '&aВи надіслали %player назви "&r%title&a" "&r%subtitle&a".'
    invalid-player: '&c%player is not a valid player.'

  # Сообщения от команды /tm amessage
  command-amessage:
    description: 'Надсилає заголовок панелі дій вказаному гравцеві'
    usage: '<player> <title>'
    sent: '&aВи надіслали %player заголовок панелі дій "&r%title&a".'
    invalid-player: '&c%player не є дійсним гравцем.'

  # Сообщения от команды /tm scoreboard
  command-scoreboard:
    description: 'Увімкнення або вимкнення табло.'
    usage: 'перемикач'
    toggled-on: '&aВи ввімкнули своє табло.'
    toggled-off: '&cВи вимкнули своє табло.'
